### PR TITLE
Add building instructions and create prebuilt binary file

### PR DESCRIPTION
**Pull request by saloniamatteo**
I added step-by-step building instructions for Linux users, and I also uploaded a prebuilt/precompiled binary for Linux (it might work with OSX, but I don't know). It also contains the necessary files it needs to run srb2kart.

### CODE REVIEW

**Comment by saloniamatteo** [comment]
The AppVeyor check may fail - but in reality everything works just fine, I've tested this myself and it works (also I've only modified the README so it shouldn't even cause problems)

**Comment by saloniamatteo** [comment]
@alama ok, reverting back to original license. Also the  buildbot config in my branch has been deleted already.

**Comment by saloniamatteo** [comment]
Hope this gets merged now! :)

**Comment by saloniamatteo** [comment]
@alama Any updates? Everything should be good already.

**Comment by Diskmaster** [comment]
Updated dependency install instructions for Gentoo (gcc is assumed to already be installed, as it's part of the tool chain, thus omitted. Also, we don't have separate -dev packages.)

```emerge --ask --noreplace --newuse git cmake p7zip nasm libpng zlib libsdl2 sdl2-mixer game-music-emu```

~~libopenmpt is omitted from the deps line as it's marked unstable and there's no stable marked version in existence. One merely has to read the relevant part of the gentoo handbook on how to get around this minor problem.~~

Edit 2: As per one of the devs, libopenmpt isn't a dependency for SRB2Kart, but SRB2 itself uses it.

I'll update this once I've successfully built it on my gentoo box. (Currently upgrading as of this comment.)

Edit: Updating after successfully building server. Definitely use cmake, but make sure at least assets are in assets/installer/ or cmake will complain about trying to find the files to MD5. libopenmpt should only be added for desktop linux usage. If there are missing features in the desktop build, check your USE flags for anything missing (like mp3 support and the like.)

Edit 3: Added --noreplace and --newuse to prevent reinstall of existing packages unless the use flags have changed on them.

**Comment by sjwhitak** [comment]
Here are updated dependency install instructions for CentOS:

`yum install gcc p7zip git gcc-c++ kernel-devel make nasm libpng-devel zlib-devel SDL2-devel SDL2_mixer-devel game-music-emu-devel libopenmpt-devel libcurl-devel`

You didn't have `libcurl-devel` and I needed it for `curl.h`.  `SDL2-devel` is also a dependency of `SDL2_mixer-devel`, so it's not necessarily explicitly needed.

**Comment by sjwhitak** [comment]
On Gentoo:
`emerge --ask --noreplace --newuse cmake p7zip nasm libpng sys-libs/zlib libsdl2 sdl2-mixer game-music-emu`
zlib was ambiguous.

**Comment by saloniamatteo** [comment]
Hello everyone,
it's been 2 years since my last comment on this issue.

To be honest, these changes should be revised, because:
1) Dependencies might've changed
2) Dependencies could be incorrect
3) When I made this pull request, I was using Ubuntu, now I switched to Gentoo, I have never used Fedora, CentOS, OpenSUSE, and so on.

Obviously, since it has been 1 to 2 years without contact from moderators/developers of this project, it's safe to say this pull request will go ignored & unmerged for even longer. I'll close this, and if the devs are interested, they can contact me (see https://saloniamatteo.github.io/en/contact.html) and we can work out a better solution.

**Comment by sjwhitak** [comment]
Thanks, I didn't think it would be merged, but this is has the best documentation for compiling on Linux. I wanted to clean it up for the different distros I used + successfully compiled for anyone else was looking for help. 
It's a pain to dig through their discord or forums to find documentation on it.

**Comment by saloniamatteo** [comment]
@sjwhitak exactly -- a couple years ago it was the same, I could barely be able to find enough information to build this for myself and I decided to share this info, but apparently the devs don't care, maybe the project is dead -- or barely alive.

**Pull request closed without merging**
